[results2d]
continous = 0.13481087196
cornerpeak = 0.19502937480
gausspeak = 0.12556144876
oscillatory = 0
productpeak = 0
discontinous = 0

[results3d]
continous = 0.049498
cornerpeak = 8.5
gausspeak = 0.0444923
oscillatory = 0
productpeak = 0
discontinous = 0